name: Build Firmware
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.15.0'

    - name: Build web dist
      working-directory: ./main/http_server/axe-os
      run: |
        npm ci
        npm run build

    - name: esp-idf build and create www.bin
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.5.2
        target: esp32s3
        path: '.'
        command: |
          # 1. Den Miner bauen
          idf.py build
          # 2. Das Web-Image (www.bin) direkt hier bauen, wo IDF_PATH bekannt ist
          python $IDF_PATH/components/spiffs/spiffsgen.py 0x1F0000 ./main/http_server/axe-os/dist ./build/www.bin

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install esptool
      run: pip install esptool

    - name: "Create factory/merged image"
      run: "./merge_bin.sh ./esp-miner-merged.bin"

    - name: upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: bitaxe-matrix-firmware
        path: |
          ./esp-miner-merged.bin
          ./build/esp-miner.bin
          ./build/www.bin
